### ISSUE TITLE
Impossible to start the bot

### ISSUE THREAD

**Issue by 0x5c** [bmonty/aa5robot#4]
The bot is impossible to start, even when following the instructions in `README.md` (both for Docker and standard installations). Here is the message it outputs before exiting (and getting restarted by forever).

```
AttributeError: 'AA5ROBot' object has no attribute 'commands'
APRS message sending not enabled.  APRS_CALLSIGN must be set in environment.
WARNING:root:Failed to create instance of CommandMessage
WARNING:slackclient.client:Failed RTM connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slackclient/client.py", line 140, in rtm_connect
    self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/slackclient/server.py", line 163, in rtm_connect
    raise SlackLoginError(reply=reply)
slackclient.server.SlackLoginError
WARNING:__main__:Connection to Slack RTM failed.
Traceback (most recent call last):
  File "aa5robot.py", line 191, in <module>
    main()
  File "aa5robot.py", line 186, in main
    aa5robot = AA5ROBot()
  File "aa5robot.py", line 38, in __init__
    self.shutdown(1)
  File "aa5robot.py", line 80, in shutdown
    for instance in self.commands:
```

**Comment by bmonty** [comment]
Do you have SLACK_BOT_TOKEN set in the environment?  Also, can you send me the command line that you used to start the script?

**Comment by 0x5c** [comment]
Yup, that result was observed with both methods, executed as-written in the README, on two distinct machines (on my end), and on my friend's machine. All three machines were running python 3.5.3.

**Comment by bmonty** [comment]
Can you connect to Slack with other scripts?  Also, please post the command line you're using.
